"""
This type stub file was generated by pyright.
"""

from enum import Enum

"""
Drawers for labels on plots.
"""
__all__ = ("TextAlignment", )
class TextAlignment(Enum):
    """Text alignment constants."""
    LEFT = ...
    CENTER = ...
    RIGHT = ...
    TOP = ...
    BOTTOM = ...


