"""
This type stub file was generated by pyright.
"""

from igraph.drawing.baseclasses import AbstractDrawer

"""
Drawing routines to draw the matrices.

This module provides implementations of matrix drawers.
"""
__all__ = ("MatplotlibDendrogramDrawer", )
class MatplotlibDendrogramDrawer(AbstractDrawer):
    """Matplotlib drawer object for dendrograms."""
    def __init__(self, ax) -> None:
        """Constructs the drawer and associates it to the given Axes.

        @param ax: the Axes on which we will draw
        """
        ...
    
    def draw(self, dendro, orientation=..., **kwds): # -> None:
        """Draws the given Dendrogram in a matplotlib Axes.

        Other keyword arguments are passed to mpl.patches.Polygon.

        @param dendro: the igraph.Dendrogram to plot.
        @param orientation: the direction of the plot. Accepted values are "lr"
          (root on the right), "rl" (root on the left), "tb" (root at the bottom),
          and "bt" (root at the top). A few aliases are available (see
          L{utils.str_to_orientation}).
        """
        ...
    


