"""
This type stub file was generated by pyright.
"""

from igraph.drawing.baseclasses import AbstractEdgeDrawer

"""Drawers for various edge styles in Matplotlib graph plots."""
__all__ = ("MatplotlibEdgeDrawer", "EdgeCollection")
PatchCollection = ...
class MatplotlibEdgeDrawer(AbstractEdgeDrawer):
    """Matplotlib-specific abstract edge drawer object."""
    def __init__(self, context, palette) -> None:
        """Constructs the edge drawer.

        @param context: a Matplotlib axes object on which the edges will be
            drawn.
        @param palette: the palette that can be used to map integer color
            indices to colors when drawing edges
        """
        ...
    
    def build_patch(self, edge, src_vertex, dest_vertex): # -> Any:
        ...
    
    def draw_directed_edge(self, edge, src_vertex, dest_vertex):
        ...
    
    def draw_undirected_edge(self, edge, src_vertex, dest_vertex):
        ...
    


class EdgeCollection(PatchCollection):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def draw(self, renderer):
        ...
    
    def get_arrow_sizes(self):
        """Same as get_arrow_size."""
        ...
    
    def get_arrow_size(self):
        """Get arrow sizes for the edges (directed only).

        @return: An array of arrow sizes.
        """
        ...
    
    def set_arrow_size(self, sizes): # -> None:
        """Set arrow sizes.

        @param sizes: A sequence of arrow sizes or a single size.
        """
        ...
    
    def set_arrow_sizes(self, sizes): # -> None:
        """Same as set_arrow_size"""
        ...
    
    def get_arrow_widths(self):
        """Same as get_arrow_width."""
        ...
    
    def get_arrow_width(self):
        """Get arrow widths for the edges (directed only).

        @return: An array of arrow widths.
        """
        ...
    
    def set_arrow_width(self, widths): # -> None:
        """Set arrow widths.

        @param widths: A sequence of arrow widths or a single width.
        """
        ...
    
    def set_arrow_widths(self, widths): # -> None:
        """Same as set_arrow_width"""
        ...
    
    @property
    def stale(self):
        ...
    
    @stale.setter
    def stale(self, val): # -> None:
        ...
    


