"""
This type stub file was generated by pyright.
"""

from igraph.drawing.baseclasses import AbstractDrawer

"""This module provides implementation for a Matplotlib-specific histogram drawer."""
__all__ = ("MatplotlibHistogramDrawer", )
class MatplotlibHistogramDrawer(AbstractDrawer):
    """Matplotlib drawer object for matrices."""
    def __init__(self, ax) -> None:
        """Constructs the drawer and associates it to the given Axes.

        @param ax: the Axes on which we will draw
        """
        ...
    
    def draw(self, matrix, **kwds): # -> None:
        """Draws the given Matrix in a matplotlib Axes.

        @param matrix: the igraph.Histogram to plot.

        """
        ...
    


