"""
This type stub file was generated by pyright.
"""

__all__ = ("HullCollection", )
PathCollection = ...
class HullCollection(PathCollection):
    """Collection for hulls connecting vertex covers/clusters.

    The class takes the normal arguments of a PathCollection, plus one argument
    called "corner_radius" that specifies how much to smoothen the polygon
    vertices into round corners. This argument can be a float or a sequence
    of floats, one for each hull to be drawn.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def draw(self, renderer):
        ...
    


