"""
This type stub file was generated by pyright.
"""

from typing import Any

__all__ = ("find_matplotlib", )
__docformat__ = ...
def find_matplotlib() -> Any:
    """Tries to import the ``matplotlib`` Python module if it is installed.
    Returns a fake module if everything fails.
    """
    ...

