"""
This type stub file was generated by pyright.
"""

from igraph.drawing.baseclasses import AbstractGraphDrawer

"""
Drawing routines to draw graphs.

This module contains routines to draw graphs on plotly surfaces.

"""
__all__ = ("PlotlyGraphDrawer", )
plotly = ...
class PlotlyGraphDrawer(AbstractGraphDrawer):
    """Graph drawer that uses a pyplot.Axes as context"""
    _shape_dict = ...
    def __init__(self, fig, vertex_drawer_factory=..., edge_drawer_factory=...) -> None:
        """Constructs the graph drawer and associates it with the plotly Figure

        @param fig: the plotly.graph_objects.Figure to draw into.

        """
        ...
    
    def draw(self, graph, *args, **kwds): # -> None:
        ...
    


