"""
This type stub file was generated by pyright.
"""

__all__ = ("PlotlyPolygonDrawer", )
plotly = ...
class PlotlyPolygonDrawer:
    """Class that is used to draw polygons in matplotlib.

    The corner points of the polygon can be set by the C{points}
    property of the drawer, or passed at construction time. Most
    drawing methods in this class also have an extra C{points}
    argument that can be used to override the set of points in the
    C{points} property."""
    def __init__(self, fig) -> None:
        """Constructs a new polygon drawer that draws on the given
        Matplotlib axes.

        @param  fig: the plotly Figure to draw on
        """
        ...
    
    def draw(self, points, corner_radius=..., **kwds): # -> None:
        """Draws a polygon to the associated axes.

        @param points: the coordinates of the corners of the polygon,
          in clockwise or counter-clockwise order, or C{None} if we are
          about to use the C{points} property of the class.
        @param corner_radius: if zero, an ordinary polygon will be drawn.
          If positive, the corners of the polygon will be rounded with
          the given radius.
        """
        ...
    


