"""
This type stub file was generated by pyright.
"""

from typing import Any

__all__ = ("find_plotly", )
__docformat__ = ...
def find_plotly() -> Any:
    """Tries to import the ``plotly`` Python module if it is installed.
    Returns a fake module if everything fails.
    """
    ...

def format_path_step(code, point_or_points): # -> str:
    """Format step in SVG path for plotly"""
    ...

def format_arc(center, radius_x, radius_y, theta1, theta2, N=..., closed=...): # -> str:
    """Approximation of an SVG-style arc

    NOTE: plotly does not currently support the native SVG "A/a" commands"""
    ...

def format_rgba(color): # -> str:
    """Format colors in a way understood by plotly"""
    ...

