"""
This type stub file was generated by pyright.
"""

from igraph.drawing.baseclasses import AbstractVertexDrawer

"""Vertices drawer. Unlike other backends, all vertices are drawn at once"""
__all__ = ("PlotlyVerticesDrawer", )
plotly = ...
class PlotlyVerticesDrawer(AbstractVertexDrawer):
    """Plotly backend-specific vertex drawer."""
    def __init__(self, fig, palette, layout) -> None:
        ...
    
    def draw(self, visual_vertex, vertex, point): # -> None:
        ...
    
    def draw_label(self, visual_vertex, point, **kwds): # -> None:
        ...
    


