"""
This type stub file was generated by pyright.
"""

from igraph.drawing.baseclasses import AbstractDrawer
from igraph.drawing.utils import BoundingBox

__all__ = ("AbstractCairoDrawer", )
class AbstractCairoDrawer(AbstractDrawer):
    """Abstract class that serves as a base class for anything that
    draws on a Cairo context within a given bounding box.

    A subclass of L{AbstractCairoDrawer} is guaranteed to have an
    attribute named C{context} that represents the Cairo context
    to draw on, and an attribute named C{bbox} for the L{BoundingBox}
    of the drawing area.
    """
    _bbox: BoundingBox
    def __init__(self, context, bbox: BoundingBox or None) -> None:
        """Constructs the drawer and associates it to the given
        Cairo context and the given L{BoundingBox}.

        @param context: the context on which we will draw
        @param bbox:    the bounding box within which we will draw.
                        Can be anything accepted by the constructor
                        of L{BoundingBox} (i.e., a 2-tuple, a 4-tuple
                        or a L{BoundingBox} object).
        """
        ...
    
    @property
    def bbox(self) -> BoundingBox:
        """The bounding box of the drawing area where this drawer will
        draw."""
        ...
    
    @bbox.setter
    def bbox(self, bbox): # -> None:
        """Sets the bounding box of the drawing area where this drawer
        will draw."""
        ...
    


