"""
This type stub file was generated by pyright.
"""

from igraph.drawing.cairo.base import AbstractCairoDrawer

"""This module provides implementation for a Cairo-specific histogram drawer"""
__all__ = ("CairoHistogramDrawer", )
class CairoHistogramDrawer(AbstractCairoDrawer):
    """Default Cairo drawer object for histograms"""
    def __init__(self, context) -> None:
        """Constructs the vertex drawer and associates it to the given
        palette.

        @param context: the context on which we will draw
        """
        ...
    
    def draw(self, histogram, **kwds): # -> None:
        """TODO"""
        ...
    


