"""
This type stub file was generated by pyright.
"""

from igraph.drawing.cairo.base import AbstractCairoDrawer

"""This module provides implementation for a Cairo-specific matrix drawer."""
__all__ = ("CairoMatrixDrawer", )
class CairoMatrixDrawer(AbstractCairoDrawer):
    """Default Cairo drawer object for matrices."""
    def __init__(self, context) -> None:
        """Constructs the vertex drawer and associates it to the given
        palette.

        @param context: the context on which we will draw
        """
        ...
    
    def draw(self, matrix, **kwds):
        """Draws the given Matrix in a Cairo context.

        @param matrix: the igraph.Matrix to plot.

        It accepts the following keyword arguments:

          - C{bbox}:    the bounding box within which we will draw.
            Can be anything accepted by the constructor of L{BoundingBox}
            (i.e., a 2-tuple, a 4-tuple or a L{BoundingBox} object).

          - C{palette}: the palette that can be used to map integer color
            indices to colors when drawing vertices

          - C{style}: the style of the plot. C{boolean} is useful for plotting
            matrices with boolean (C{True}/C{False} or 0/1) values: C{False}
            will be shown with a white box and C{True} with a black box.
            C{palette} uses the given palette to represent numbers by colors,
            the minimum will be assigned to palette color index 0 and the maximum
            will be assigned to the length of the palette. C{None} draws transparent
            cell backgrounds only. The default style is C{boolean} (but it may
            change in the future). C{None} values in the matrix are treated
            specially in both cases: nothing is drawn in the cell corresponding
            to C{None}.

          - C{square}: whether the cells of the matrix should be square or not.
            Default is C{True}.

          - C{grid_width}: line width of the grid shown on the matrix. If zero or
            negative, the grid is turned off. The grid is also turned off if the size
            of a cell is less than three times the given line width. Default is C{1}.
            Fractional widths are also allowed.

          - C{border_width}: line width of the border drawn around the matrix.
            If zero or negative, the border is turned off. Default is C{1}.

          - C{row_names}: the names of the rows

          - C{col_names}: the names of the columns.

          - C{values}: values to be displayed in the cells. If C{None} or
            C{False}, no values are displayed. If C{True}, the values come
            from the matrix being plotted. If it is another matrix, the
            values of that matrix are shown in the cells. In this case,
            the shape of the value matrix must match the shape of the
            matrix being plotted.

          - C{value_format}: a format string or a callable that specifies how
            the values should be plotted. If it is a callable, it must be a
            function that expects a single value and returns a string.
            Example: C{"%#.2f"} for floating-point numbers with always exactly
            two digits after the decimal point. See the Python documentation of
            the C{%} operator for details on the format string. If the format
            string is not given, it defaults to the C{str} function.

        If only the row names or the column names are given and the matrix
        is square-shaped, the same names are used for both column and row
        names.
        """
        ...
    


