"""
This type stub file was generated by pyright.
"""

from igraph.drawing.cairo.base import AbstractCairoDrawer

"""This module provides implementation for a Cairo-specific palette drawer"""
__all__ = ("CairoPaletteDrawer", )
class CairoPaletteDrawer(AbstractCairoDrawer):
    """Default Cairo drawer object for palettes"""
    def __init__(self, context) -> None:
        """Constructs the vertex drawer and associates it to the given
        palette.

        @param context: the context on which we will draw
        """
        ...
    
    def draw(self, palette, **kwds): # -> None:
        """TODO"""
        ...
    


