"""
This type stub file was generated by pyright.
"""

from typing import Any

__all__ = ("find_cairo", )
__docformat__ = ...
def find_cairo() -> Any:
    """Tries to import the ``cairo`` Python module if it is installed,
    also trying ``cairocffi`` (a drop-in replacement of ``cairo``).
    Returns a fake module if everything fails.
    """
    ...

