"""
This type stub file was generated by pyright.
"""

from igraph.operators.functions import disjoint_union, intersection, union
from igraph.operators.methods import __add__, __and__, __iadd__, __isub__, __mul__, __or__, __sub__, _disjoint_union, _intersection, _union

"""Implementation of union, disjoint union and intersection operators."""
__all__ = ("disjoint_union", "union", "intersection", "operator_method_registry")
operator_method_registry = ...
